[package]
name = "merkletree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
sha2 = "0.10.7"
rayon = "1.7.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmarks"
harness = false


